name: CI/CD DevOps TP 2025

# Déclenchement du pipeline sur push ou pull request
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  # ========================
  # 1️⃣ Job : Build & Test
  # ========================
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : Build et tests Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

      